enum 80036 "Tipo Pedido"
{
    //OptionMembers = 'Telefono,Fax,Comercial,PDA,Web,Otros';
    value(0; Telefono)
    {
        Caption = 'Teléfono';
    }
    value(1; Fax)
    {
        Caption = 'Fax';
    }
    value(2; Comercial)
    {
        Caption = 'Comercial';
    }
    value(3; PDA)
    {
        Caption = 'PDA';
    }
    value(4; Web)
    {
        Caption = 'Web';
    }
    value(5; Otros)
    {
        Caption = 'Otros';
    }
}